blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blogapp.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blogapp.urls')),
    url(r'',include('comments.urls')),
    url(r'all/rss/$',AllPostsRssFeed(),name='rss'),
    url(r'^search/', include('haystack.urls')),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible
# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blogapp.Post')

    def __str__(self):
        return self.text[:20]

templates/blog/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category }}</a></span>
                            {% for tag in post.tags.all %}
                            <span class="post-category"><a href="#">{{ tag.name }}</a></span>
                            {% endfor %}
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }}阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.nam.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评价
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
    <aside class="col-md-4">
        <div class="widget widget-content">
            <h3 class="widget-title">文章目录</h3>
            <ul>
                <li>
                    <a href="#">教程特点</a>
                </li>
                <li>
                    <a href="#">谁适合这个教程</a>
                </li>
                <li>
                    <a href="#">在线预览</a>
                </li>
                <li>
                    <a href="#">资源列表</a>
                </li>
                <li>
                    <a href="#">获取帮助</a>
                </li>
            </ul>
        </div>
    </aside>
{% endblock toc %}

templates/blog/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    {% for tag in post.tags.all %}
                            <span class="post-category"><a href="#">{{ tag.name }}</a></span>
                            {% endfor %}
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.body|truncatechars:54 }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    {% if is_paginated %}
    <div class="pagination">
      {% if first %}
        <a href="?page=1">1</a>
      {% endif %}
      {% if left %}
        {% if left_has_more %}
            <span>...</span>
        {% endif %}
        {% for i in left %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
      {% endif %}
      <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
      {% if right %}
        {% for i in right %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if right_has_more %}
            <span>...</span>
        {% endif %}
      {% endif %}
      {% if last %}
        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
      {% endif %}
    </div>
{% endif %}
{% endblock main %}